[pytest]
faulthandler_timeout=5
